version: '3.8'

services:
  web:
#    restart: always
    build: ./posgraduacao
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
#    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
#    restart: always
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pos
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
#    restart: always
    image: redis:7
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata:
